// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gojangframework/gojang/app/gojang/models/adminsetting"
	"github.com/google/uuid"
)

// AdminSetting is the model entity for the AdminSetting schema.
type AdminSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Admin preference key (e.g., 'admin.workspace.sidebar_order')
	Key string `json:"key,omitempty"`
	// Admin preference value (JSON or plain text)
	Value        string `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminsetting.FieldKey, adminsetting.FieldValue:
			values[i] = new(sql.NullString)
		case adminsetting.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminSetting fields.
func (_m *AdminSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminsetting.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case adminsetting.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case adminsetting.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the AdminSetting.
// This includes values selected through modifiers, order, etc.
func (_m *AdminSetting) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AdminSetting.
// Note that you need to call AdminSetting.Unwrap() before calling this method if this AdminSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminSetting) Update() *AdminSettingUpdateOne {
	return NewAdminSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminSetting) Unwrap() *AdminSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("models: AdminSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminSetting) String() string {
	var builder strings.Builder
	builder.WriteString("AdminSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// AdminSettings is a parsable slice of AdminSetting.
type AdminSettings []*AdminSetting
