// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gojangframework/gojang/app/gojang/models/adminsetting"
	"github.com/google/uuid"
)

// AdminSettingCreate is the builder for creating a AdminSetting entity.
type AdminSettingCreate struct {
	config
	mutation *AdminSettingMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *AdminSettingCreate) SetKey(v string) *AdminSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *AdminSettingCreate) SetValue(v string) *AdminSettingCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AdminSettingCreate) SetID(v uuid.UUID) *AdminSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AdminSettingCreate) SetNillableID(v *uuid.UUID) *AdminSettingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AdminSettingMutation object of the builder.
func (_c *AdminSettingCreate) Mutation() *AdminSettingMutation {
	return _c.mutation
}

// Save creates the AdminSetting in the database.
func (_c *AdminSettingCreate) Save(ctx context.Context) (*AdminSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminSettingCreate) SaveX(ctx context.Context) *AdminSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminSettingCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := adminsetting.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`models: missing required field "AdminSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := adminsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`models: validator failed for field "AdminSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`models: missing required field "AdminSetting.value"`)}
	}
	return nil
}

func (_c *AdminSettingCreate) sqlSave(ctx context.Context) (*AdminSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminSettingCreate) createSpec() (*AdminSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminsetting.Table, sqlgraph.NewFieldSpec(adminsetting.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(adminsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(adminsetting.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// AdminSettingCreateBulk is the builder for creating many AdminSetting entities in bulk.
type AdminSettingCreateBulk struct {
	config
	err      error
	builders []*AdminSettingCreate
}

// Save creates the AdminSetting entities in the database.
func (_c *AdminSettingCreateBulk) Save(ctx context.Context) ([]*AdminSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminSettingCreateBulk) SaveX(ctx context.Context) []*AdminSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
