// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gojangframework/gojang/app/gojang/models/post"
	"github.com/gojangframework/gojang/app/gojang/models/predicate"
	"github.com/gojangframework/gojang/app/gojang/models/user"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdate) SetIsActive(v bool) *UserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsStaff sets the "is_staff" field.
func (_u *UserUpdate) SetIsStaff(v bool) *UserUpdate {
	_u.mutation.SetIsStaff(v)
	return _u
}

// SetNillableIsStaff sets the "is_staff" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsStaff(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsStaff(*v)
	}
	return _u
}

// SetIsSuperuser sets the "is_superuser" field.
func (_u *UserUpdate) SetIsSuperuser(v bool) *UserUpdate {
	_u.mutation.SetIsSuperuser(v)
	return _u
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsSuperuser(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsSuperuser(*v)
	}
	return _u
}

// SetIsEmailVerified sets the "is_email_verified" field.
func (_u *UserUpdate) SetIsEmailVerified(v bool) *UserUpdate {
	_u.mutation.SetIsEmailVerified(v)
	return _u
}

// SetNillableIsEmailVerified sets the "is_email_verified" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsEmailVerified(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsEmailVerified(*v)
	}
	return _u
}

// SetEmailVerificationToken sets the "email_verification_token" field.
func (_u *UserUpdate) SetEmailVerificationToken(v string) *UserUpdate {
	_u.mutation.SetEmailVerificationToken(v)
	return _u
}

// SetNillableEmailVerificationToken sets the "email_verification_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmailVerificationToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmailVerificationToken(*v)
	}
	return _u
}

// ClearEmailVerificationToken clears the value of the "email_verification_token" field.
func (_u *UserUpdate) ClearEmailVerificationToken() *UserUpdate {
	_u.mutation.ClearEmailVerificationToken()
	return _u
}

// SetEmailVerificationExpiry sets the "email_verification_expiry" field.
func (_u *UserUpdate) SetEmailVerificationExpiry(v time.Time) *UserUpdate {
	_u.mutation.SetEmailVerificationExpiry(v)
	return _u
}

// SetNillableEmailVerificationExpiry sets the "email_verification_expiry" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmailVerificationExpiry(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetEmailVerificationExpiry(*v)
	}
	return _u
}

// ClearEmailVerificationExpiry clears the value of the "email_verification_expiry" field.
func (_u *UserUpdate) ClearEmailVerificationExpiry() *UserUpdate {
	_u.mutation.ClearEmailVerificationExpiry()
	return _u
}

// SetPasswordResetToken sets the "password_reset_token" field.
func (_u *UserUpdate) SetPasswordResetToken(v string) *UserUpdate {
	_u.mutation.SetPasswordResetToken(v)
	return _u
}

// SetNillablePasswordResetToken sets the "password_reset_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordResetToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordResetToken(*v)
	}
	return _u
}

// ClearPasswordResetToken clears the value of the "password_reset_token" field.
func (_u *UserUpdate) ClearPasswordResetToken() *UserUpdate {
	_u.mutation.ClearPasswordResetToken()
	return _u
}

// SetPasswordResetExpiry sets the "password_reset_expiry" field.
func (_u *UserUpdate) SetPasswordResetExpiry(v time.Time) *UserUpdate {
	_u.mutation.SetPasswordResetExpiry(v)
	return _u
}

// SetNillablePasswordResetExpiry sets the "password_reset_expiry" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordResetExpiry(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetPasswordResetExpiry(*v)
	}
	return _u
}

// ClearPasswordResetExpiry clears the value of the "password_reset_expiry" field.
func (_u *UserUpdate) ClearPasswordResetExpiry() *UserUpdate {
	_u.mutation.ClearPasswordResetExpiry()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *UserUpdate) SetLastLogin(v time.Time) *UserUpdate {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLogin(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *UserUpdate) ClearLastLogin() *UserUpdate {
	_u.mutation.ClearLastLogin()
	return _u
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *UserUpdate) AddPostIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *UserUpdate) AddPosts(v ...*Post) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *UserUpdate) ClearPosts() *UserUpdate {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *UserUpdate) RemovePostIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *UserUpdate) RemovePosts(v ...*Post) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`models: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsStaff(); ok {
		_spec.SetField(user.FieldIsStaff, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuperuser(); ok {
		_spec.SetField(user.FieldIsSuperuser, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEmailVerified(); ok {
		_spec.SetField(user.FieldIsEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EmailVerificationToken(); ok {
		_spec.SetField(user.FieldEmailVerificationToken, field.TypeString, value)
	}
	if _u.mutation.EmailVerificationTokenCleared() {
		_spec.ClearField(user.FieldEmailVerificationToken, field.TypeString)
	}
	if value, ok := _u.mutation.EmailVerificationExpiry(); ok {
		_spec.SetField(user.FieldEmailVerificationExpiry, field.TypeTime, value)
	}
	if _u.mutation.EmailVerificationExpiryCleared() {
		_spec.ClearField(user.FieldEmailVerificationExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.PasswordResetToken(); ok {
		_spec.SetField(user.FieldPasswordResetToken, field.TypeString, value)
	}
	if _u.mutation.PasswordResetTokenCleared() {
		_spec.ClearField(user.FieldPasswordResetToken, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordResetExpiry(); ok {
		_spec.SetField(user.FieldPasswordResetExpiry, field.TypeTime, value)
	}
	if _u.mutation.PasswordResetExpiryCleared() {
		_spec.ClearField(user.FieldPasswordResetExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(user.FieldLastLogin, field.TypeTime)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdateOne) SetIsActive(v bool) *UserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsStaff sets the "is_staff" field.
func (_u *UserUpdateOne) SetIsStaff(v bool) *UserUpdateOne {
	_u.mutation.SetIsStaff(v)
	return _u
}

// SetNillableIsStaff sets the "is_staff" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsStaff(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsStaff(*v)
	}
	return _u
}

// SetIsSuperuser sets the "is_superuser" field.
func (_u *UserUpdateOne) SetIsSuperuser(v bool) *UserUpdateOne {
	_u.mutation.SetIsSuperuser(v)
	return _u
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsSuperuser(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsSuperuser(*v)
	}
	return _u
}

// SetIsEmailVerified sets the "is_email_verified" field.
func (_u *UserUpdateOne) SetIsEmailVerified(v bool) *UserUpdateOne {
	_u.mutation.SetIsEmailVerified(v)
	return _u
}

// SetNillableIsEmailVerified sets the "is_email_verified" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsEmailVerified(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsEmailVerified(*v)
	}
	return _u
}

// SetEmailVerificationToken sets the "email_verification_token" field.
func (_u *UserUpdateOne) SetEmailVerificationToken(v string) *UserUpdateOne {
	_u.mutation.SetEmailVerificationToken(v)
	return _u
}

// SetNillableEmailVerificationToken sets the "email_verification_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmailVerificationToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmailVerificationToken(*v)
	}
	return _u
}

// ClearEmailVerificationToken clears the value of the "email_verification_token" field.
func (_u *UserUpdateOne) ClearEmailVerificationToken() *UserUpdateOne {
	_u.mutation.ClearEmailVerificationToken()
	return _u
}

// SetEmailVerificationExpiry sets the "email_verification_expiry" field.
func (_u *UserUpdateOne) SetEmailVerificationExpiry(v time.Time) *UserUpdateOne {
	_u.mutation.SetEmailVerificationExpiry(v)
	return _u
}

// SetNillableEmailVerificationExpiry sets the "email_verification_expiry" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmailVerificationExpiry(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetEmailVerificationExpiry(*v)
	}
	return _u
}

// ClearEmailVerificationExpiry clears the value of the "email_verification_expiry" field.
func (_u *UserUpdateOne) ClearEmailVerificationExpiry() *UserUpdateOne {
	_u.mutation.ClearEmailVerificationExpiry()
	return _u
}

// SetPasswordResetToken sets the "password_reset_token" field.
func (_u *UserUpdateOne) SetPasswordResetToken(v string) *UserUpdateOne {
	_u.mutation.SetPasswordResetToken(v)
	return _u
}

// SetNillablePasswordResetToken sets the "password_reset_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordResetToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordResetToken(*v)
	}
	return _u
}

// ClearPasswordResetToken clears the value of the "password_reset_token" field.
func (_u *UserUpdateOne) ClearPasswordResetToken() *UserUpdateOne {
	_u.mutation.ClearPasswordResetToken()
	return _u
}

// SetPasswordResetExpiry sets the "password_reset_expiry" field.
func (_u *UserUpdateOne) SetPasswordResetExpiry(v time.Time) *UserUpdateOne {
	_u.mutation.SetPasswordResetExpiry(v)
	return _u
}

// SetNillablePasswordResetExpiry sets the "password_reset_expiry" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordResetExpiry(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordResetExpiry(*v)
	}
	return _u
}

// ClearPasswordResetExpiry clears the value of the "password_reset_expiry" field.
func (_u *UserUpdateOne) ClearPasswordResetExpiry() *UserUpdateOne {
	_u.mutation.ClearPasswordResetExpiry()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *UserUpdateOne) SetLastLogin(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLogin(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *UserUpdateOne) ClearLastLogin() *UserUpdateOne {
	_u.mutation.ClearLastLogin()
	return _u
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *UserUpdateOne) AddPostIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *UserUpdateOne) AddPosts(v ...*Post) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *UserUpdateOne) ClearPosts() *UserUpdateOne {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *UserUpdateOne) RemovePostIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *UserUpdateOne) RemovePosts(v ...*Post) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`models: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`models: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsStaff(); ok {
		_spec.SetField(user.FieldIsStaff, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuperuser(); ok {
		_spec.SetField(user.FieldIsSuperuser, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEmailVerified(); ok {
		_spec.SetField(user.FieldIsEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EmailVerificationToken(); ok {
		_spec.SetField(user.FieldEmailVerificationToken, field.TypeString, value)
	}
	if _u.mutation.EmailVerificationTokenCleared() {
		_spec.ClearField(user.FieldEmailVerificationToken, field.TypeString)
	}
	if value, ok := _u.mutation.EmailVerificationExpiry(); ok {
		_spec.SetField(user.FieldEmailVerificationExpiry, field.TypeTime, value)
	}
	if _u.mutation.EmailVerificationExpiryCleared() {
		_spec.ClearField(user.FieldEmailVerificationExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.PasswordResetToken(); ok {
		_spec.SetField(user.FieldPasswordResetToken, field.TypeString, value)
	}
	if _u.mutation.PasswordResetTokenCleared() {
		_spec.ClearField(user.FieldPasswordResetToken, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordResetExpiry(); ok {
		_spec.SetField(user.FieldPasswordResetExpiry, field.TypeTime, value)
	}
	if _u.mutation.PasswordResetExpiryCleared() {
		_spec.ClearField(user.FieldPasswordResetExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(user.FieldLastLogin, field.TypeTime)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
