// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gojangframework/gojang/app/gojang/models/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsActive, v))
}

// IsStaff applies equality check predicate on the "is_staff" field. It's identical to IsStaffEQ.
func IsStaff(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsStaff, v))
}

// IsSuperuser applies equality check predicate on the "is_superuser" field. It's identical to IsSuperuserEQ.
func IsSuperuser(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsSuperuser, v))
}

// IsEmailVerified applies equality check predicate on the "is_email_verified" field. It's identical to IsEmailVerifiedEQ.
func IsEmailVerified(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsEmailVerified, v))
}

// EmailVerificationToken applies equality check predicate on the "email_verification_token" field. It's identical to EmailVerificationTokenEQ.
func EmailVerificationToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmailVerificationToken, v))
}

// EmailVerificationExpiry applies equality check predicate on the "email_verification_expiry" field. It's identical to EmailVerificationExpiryEQ.
func EmailVerificationExpiry(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmailVerificationExpiry, v))
}

// PasswordResetToken applies equality check predicate on the "password_reset_token" field. It's identical to PasswordResetTokenEQ.
func PasswordResetToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordResetToken, v))
}

// PasswordResetExpiry applies equality check predicate on the "password_reset_expiry" field. It's identical to PasswordResetExpiryEQ.
func PasswordResetExpiry(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordResetExpiry, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastLogin applies equality check predicate on the "last_login" field. It's identical to LastLoginEQ.
func LastLogin(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLogin, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsActive, v))
}

// IsStaffEQ applies the EQ predicate on the "is_staff" field.
func IsStaffEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsStaff, v))
}

// IsStaffNEQ applies the NEQ predicate on the "is_staff" field.
func IsStaffNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsStaff, v))
}

// IsSuperuserEQ applies the EQ predicate on the "is_superuser" field.
func IsSuperuserEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsSuperuser, v))
}

// IsSuperuserNEQ applies the NEQ predicate on the "is_superuser" field.
func IsSuperuserNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsSuperuser, v))
}

// IsEmailVerifiedEQ applies the EQ predicate on the "is_email_verified" field.
func IsEmailVerifiedEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsEmailVerified, v))
}

// IsEmailVerifiedNEQ applies the NEQ predicate on the "is_email_verified" field.
func IsEmailVerifiedNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsEmailVerified, v))
}

// EmailVerificationTokenEQ applies the EQ predicate on the "email_verification_token" field.
func EmailVerificationTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenNEQ applies the NEQ predicate on the "email_verification_token" field.
func EmailVerificationTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenIn applies the In predicate on the "email_verification_token" field.
func EmailVerificationTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmailVerificationToken, vs...))
}

// EmailVerificationTokenNotIn applies the NotIn predicate on the "email_verification_token" field.
func EmailVerificationTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmailVerificationToken, vs...))
}

// EmailVerificationTokenGT applies the GT predicate on the "email_verification_token" field.
func EmailVerificationTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenGTE applies the GTE predicate on the "email_verification_token" field.
func EmailVerificationTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenLT applies the LT predicate on the "email_verification_token" field.
func EmailVerificationTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenLTE applies the LTE predicate on the "email_verification_token" field.
func EmailVerificationTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenContains applies the Contains predicate on the "email_verification_token" field.
func EmailVerificationTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenHasPrefix applies the HasPrefix predicate on the "email_verification_token" field.
func EmailVerificationTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenHasSuffix applies the HasSuffix predicate on the "email_verification_token" field.
func EmailVerificationTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenIsNil applies the IsNil predicate on the "email_verification_token" field.
func EmailVerificationTokenIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmailVerificationToken))
}

// EmailVerificationTokenNotNil applies the NotNil predicate on the "email_verification_token" field.
func EmailVerificationTokenNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmailVerificationToken))
}

// EmailVerificationTokenEqualFold applies the EqualFold predicate on the "email_verification_token" field.
func EmailVerificationTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmailVerificationToken, v))
}

// EmailVerificationTokenContainsFold applies the ContainsFold predicate on the "email_verification_token" field.
func EmailVerificationTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmailVerificationToken, v))
}

// EmailVerificationExpiryEQ applies the EQ predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmailVerificationExpiry, v))
}

// EmailVerificationExpiryNEQ applies the NEQ predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmailVerificationExpiry, v))
}

// EmailVerificationExpiryIn applies the In predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmailVerificationExpiry, vs...))
}

// EmailVerificationExpiryNotIn applies the NotIn predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmailVerificationExpiry, vs...))
}

// EmailVerificationExpiryGT applies the GT predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmailVerificationExpiry, v))
}

// EmailVerificationExpiryGTE applies the GTE predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmailVerificationExpiry, v))
}

// EmailVerificationExpiryLT applies the LT predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmailVerificationExpiry, v))
}

// EmailVerificationExpiryLTE applies the LTE predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmailVerificationExpiry, v))
}

// EmailVerificationExpiryIsNil applies the IsNil predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmailVerificationExpiry))
}

// EmailVerificationExpiryNotNil applies the NotNil predicate on the "email_verification_expiry" field.
func EmailVerificationExpiryNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmailVerificationExpiry))
}

// PasswordResetTokenEQ applies the EQ predicate on the "password_reset_token" field.
func PasswordResetTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordResetToken, v))
}

// PasswordResetTokenNEQ applies the NEQ predicate on the "password_reset_token" field.
func PasswordResetTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordResetToken, v))
}

// PasswordResetTokenIn applies the In predicate on the "password_reset_token" field.
func PasswordResetTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordResetToken, vs...))
}

// PasswordResetTokenNotIn applies the NotIn predicate on the "password_reset_token" field.
func PasswordResetTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordResetToken, vs...))
}

// PasswordResetTokenGT applies the GT predicate on the "password_reset_token" field.
func PasswordResetTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordResetToken, v))
}

// PasswordResetTokenGTE applies the GTE predicate on the "password_reset_token" field.
func PasswordResetTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordResetToken, v))
}

// PasswordResetTokenLT applies the LT predicate on the "password_reset_token" field.
func PasswordResetTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordResetToken, v))
}

// PasswordResetTokenLTE applies the LTE predicate on the "password_reset_token" field.
func PasswordResetTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordResetToken, v))
}

// PasswordResetTokenContains applies the Contains predicate on the "password_reset_token" field.
func PasswordResetTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordResetToken, v))
}

// PasswordResetTokenHasPrefix applies the HasPrefix predicate on the "password_reset_token" field.
func PasswordResetTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordResetToken, v))
}

// PasswordResetTokenHasSuffix applies the HasSuffix predicate on the "password_reset_token" field.
func PasswordResetTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordResetToken, v))
}

// PasswordResetTokenIsNil applies the IsNil predicate on the "password_reset_token" field.
func PasswordResetTokenIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPasswordResetToken))
}

// PasswordResetTokenNotNil applies the NotNil predicate on the "password_reset_token" field.
func PasswordResetTokenNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPasswordResetToken))
}

// PasswordResetTokenEqualFold applies the EqualFold predicate on the "password_reset_token" field.
func PasswordResetTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordResetToken, v))
}

// PasswordResetTokenContainsFold applies the ContainsFold predicate on the "password_reset_token" field.
func PasswordResetTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordResetToken, v))
}

// PasswordResetExpiryEQ applies the EQ predicate on the "password_reset_expiry" field.
func PasswordResetExpiryEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordResetExpiry, v))
}

// PasswordResetExpiryNEQ applies the NEQ predicate on the "password_reset_expiry" field.
func PasswordResetExpiryNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordResetExpiry, v))
}

// PasswordResetExpiryIn applies the In predicate on the "password_reset_expiry" field.
func PasswordResetExpiryIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordResetExpiry, vs...))
}

// PasswordResetExpiryNotIn applies the NotIn predicate on the "password_reset_expiry" field.
func PasswordResetExpiryNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordResetExpiry, vs...))
}

// PasswordResetExpiryGT applies the GT predicate on the "password_reset_expiry" field.
func PasswordResetExpiryGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordResetExpiry, v))
}

// PasswordResetExpiryGTE applies the GTE predicate on the "password_reset_expiry" field.
func PasswordResetExpiryGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordResetExpiry, v))
}

// PasswordResetExpiryLT applies the LT predicate on the "password_reset_expiry" field.
func PasswordResetExpiryLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordResetExpiry, v))
}

// PasswordResetExpiryLTE applies the LTE predicate on the "password_reset_expiry" field.
func PasswordResetExpiryLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordResetExpiry, v))
}

// PasswordResetExpiryIsNil applies the IsNil predicate on the "password_reset_expiry" field.
func PasswordResetExpiryIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPasswordResetExpiry))
}

// PasswordResetExpiryNotNil applies the NotNil predicate on the "password_reset_expiry" field.
func PasswordResetExpiryNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPasswordResetExpiry))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastLoginEQ applies the EQ predicate on the "last_login" field.
func LastLoginEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLogin, v))
}

// LastLoginNEQ applies the NEQ predicate on the "last_login" field.
func LastLoginNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastLogin, v))
}

// LastLoginIn applies the In predicate on the "last_login" field.
func LastLoginIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastLogin, vs...))
}

// LastLoginNotIn applies the NotIn predicate on the "last_login" field.
func LastLoginNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastLogin, vs...))
}

// LastLoginGT applies the GT predicate on the "last_login" field.
func LastLoginGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastLogin, v))
}

// LastLoginGTE applies the GTE predicate on the "last_login" field.
func LastLoginGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastLogin, v))
}

// LastLoginLT applies the LT predicate on the "last_login" field.
func LastLoginLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastLogin, v))
}

// LastLoginLTE applies the LTE predicate on the "last_login" field.
func LastLoginLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastLogin, v))
}

// LastLoginIsNil applies the IsNil predicate on the "last_login" field.
func LastLoginIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLastLogin))
}

// LastLoginNotNil applies the NotNil predicate on the "last_login" field.
func LastLoginNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLastLogin))
}

// HasPosts applies the HasEdge predicate on the "posts" edge.
func HasPosts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PostsTable, PostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostsWith applies the HasEdge predicate on the "posts" edge with a given conditions (other predicates).
func HasPostsWith(preds ...predicate.Post) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
