// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminSetting is the predicate function for adminsetting builders.
type AdminSetting func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
